server:
  port: 8883

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:

    registerWithEureka: true

    fetchRegistry: true
    serviceUrl:
 
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost/mydb
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  application:
    name: userservice
