server:
  port: 8883

eureka:
  instance:
    
    preferIpAddress: true
    hostname: localhost
  client:
    
    registerWithEureka: true
   
    fetchRegistry: true
    serviceUrl:
     
      defaultZone: http://192.168.163.130:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://192.168.0.198/mysql
    password: ps123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  application:
    name: userservice
